"""
Test Verilator coverage parser
"""

from pathlib import Path
import tempfile


def create_sample_verilator_dat(path: Path) -> None:
    """Create a sample Verilator .dat file for testing"""
    content = """# Verilator coverage database
# Generated by Verilator 5.006 2024-01-15
TN:test_adder
SF:rtl/adder.sv
FN:8,adder
FNDA:1000,adder
FNF:1
FNH:1
DA:8,1000
DA:9,1000
DA:10,1000
DA:11,1000
DA:12,1000
DA:13,850
DA:14,850
DA:15,850
DA:16,750
DA:17,750
DA:18,1000
DA:19,150
DA:20,150
DA:21,0
DA:22,0
LF:15
LH:13
BRDA:13,0,0,850
BRDA:13,0,1,150
BRDA:16,1,0,750
BRDA:16,1,1,250
BRF:4
BRH:4
end_of_record
SF:rtl/full_adder.sv
FN:5,full_adder
FNDA:8000,full_adder
DA:5,8000
DA:6,8000
DA:7,8000
DA:8,8000
DA:9,8000
DA:10,8000
LF:6
LH:6
BRF:0
BRH:0
end_of_record
"""
    path.write_text(content)


def test_can_parse():
    """Test Verilator format detection"""
    from step5_coverage.parsers.verilator_parser import VerilatorParser
    
    parser = VerilatorParser()
    
    # Test with .dat extension and Verilator content
    with tempfile.NamedTemporaryFile(suffix='.dat', delete=False) as f:
        f.write(b"# Verilator coverage database\n")
        f.write(b"SF:test.sv\nDA:10,5\n")
        temp_path = Path(f.name)
    
    try:
        assert parser.can_parse(temp_path)
    finally:
        temp_path.unlink()
    
    # Test with wrong extension
    with tempfile.NamedTemporaryFile(suffix='.txt', delete=False) as f:
        f.write(b"# Verilator coverage database\n")
        temp_path = Path(f.name)
    
    try:
        assert not parser.can_parse(temp_path)
    finally:
        temp_path.unlink()


def test_get_format():
    """Test format identifier"""
    from step5_coverage.parsers.verilator_parser import VerilatorParser
    from step5_coverage.models import CoverageFormat
    
    parser = VerilatorParser()
    assert parser.get_format() == CoverageFormat.VERILATOR_DAT


def test_parse_python():
    """Test Python-based parsing"""
    from step5_coverage.parsers.verilator_parser import VerilatorParser
    
    parser = VerilatorParser()
    
    # Create sample .dat file
    with tempfile.NamedTemporaryFile(suffix='.dat', delete=False) as f:
        temp_path = Path(f.name)
    
    try:
        create_sample_verilator_dat(temp_path)
        
        # Parse with Python parser
        result = parser._parse_with_python(temp_path)
        
        assert result.success
        assert result.coverage is not None
        
        # Check parsed data
        module = result.coverage
        assert len(module.files) == 2
        assert "rtl/adder.sv" in module.files
        assert "rtl/full_adder.sv" in module.files
        
        # Check adder.sv coverage
        adder_file = module.files["rtl/adder.sv"]
        assert len(adder_file.lines) == 15
        assert adder_file.lines[8].hit_count == 1000
        assert adder_file.lines[21].hit_count == 0
        assert adder_file.lines[13].is_covered
        assert not adder_file.lines[21].is_covered
        
        # Check branches
        assert len(adder_file.branches) == 4
        
        # Check full_adder.sv coverage
        full_adder_file = module.files["rtl/full_adder.sv"]
        assert len(full_adder_file.lines) == 6
        assert full_adder_file.lines[5].hit_count == 8000
        
    finally:
        temp_path.unlink()


def test_parse_file():
    """Test complete parse_file method"""
    from step5_coverage.parsers.verilator_parser import VerilatorParser
    
    parser = VerilatorParser()
    
    with tempfile.NamedTemporaryFile(suffix='.dat', delete=False) as f:
        temp_path = Path(f.name)
    
    try:
        create_sample_verilator_dat(temp_path)
        
        # Parse file
        result = parser.parse_file(temp_path)
        
        assert result.success
        assert result.coverage is not None
        assert result.parse_time_ms >= 0
        
        # Verify coverage metrics
        module = result.coverage
        adder = module.files["rtl/adder.sv"]
        
        # Line coverage: 13 of 15 lines covered = 86.7%
        assert adder.total_lines == 15
        assert adder.covered_lines == 13
        assert 86.0 < adder.line_coverage_percent < 87.0
        
        # Branch coverage: 4 of 4 branches covered = 100%
        assert adder.total_branches == 4
        assert adder.covered_branches == 4
        assert adder.branch_coverage_percent == 100.0
        
    finally:
        temp_path.unlink()


def test_merge_python():
    """Test Python-based merging"""
    from step5_coverage.parsers.verilator_parser import VerilatorParser
    
    parser = VerilatorParser()
    
    # Create two .dat files with overlapping coverage
    file1_content = """# Verilator coverage
SF:test.sv
DA:10,5
DA:20,3
end_of_record
"""
    
    file2_content = """# Verilator coverage
SF:test.sv
DA:10,7
DA:30,2
end_of_record
"""
    
    files = []
    for content in [file1_content, file2_content]:
        with tempfile.NamedTemporaryFile(suffix='.dat', delete=False, mode='w') as f:
            f.write(content)
            files.append(Path(f.name))
    
    try:
        # Merge files
        result = parser.merge_coverage(files)
        
        assert result.success
        assert result.merged_coverage is not None
        
        # Check merged data
        merged = result.merged_coverage
        test_file = merged.files["test.sv"]
        
        # Line 10: 5 + 7 = 12
        assert test_file.lines[10].hit_count == 12
        
        # Line 20: only in file1 = 3
        assert test_file.lines[20].hit_count == 3
        
        # Line 30: only in file2 = 2
        assert test_file.lines[30].hit_count == 2
        
        # Total lines = 3
        assert len(test_file.lines) == 3
        
    finally:
        for f in files:
            f.unlink()


def test_validate_dat_file():
    """Test .dat file validation"""
    from step5_coverage.parsers.verilator_parser import VerilatorParser
    
    parser = VerilatorParser()
    
    # Valid file
    with tempfile.NamedTemporaryFile(suffix='.dat', delete=False) as f:
        temp_path = Path(f.name)
    
    try:
        create_sample_verilator_dat(temp_path)
        
        is_valid, errors = parser.validate_dat_file(temp_path)
        assert is_valid
        assert len(errors) == 0
        
    finally:
        temp_path.unlink()
    
    # Invalid file (no SF records)
    with tempfile.NamedTemporaryFile(suffix='.dat', delete=False) as f:
        f.write(b"# Verilator coverage\nDA:10,5\n")
        temp_path = Path(f.name)
    
    try:
        is_valid, errors = parser.validate_dat_file(temp_path)
        assert not is_valid
        assert any("source file" in e.lower() for e in errors)
        
    finally:
        temp_path.unlink()


def test_coverage_metrics():
    """Test coverage metric calculations"""
    from step5_coverage.parsers.verilator_parser import VerilatorParser
    
    parser = VerilatorParser()
    
    with tempfile.NamedTemporaryFile(suffix='.dat', delete=False) as f:
        temp_path = Path(f.name)
    
    try:
        create_sample_verilator_dat(temp_path)
        result = parser.parse_file(temp_path)
        
        module = result.coverage
        
        # Test adder.sv metrics
        adder = module.files["rtl/adder.sv"]
        
        # Uncovered lines
        uncovered = adder.uncovered_lines
        assert 21 in uncovered
        assert 22 in uncovered
        assert len(uncovered) == 2
        
        # Line coverage percentage
        assert adder.total_lines == 15
        assert adder.covered_lines == 13
        
        # Branch coverage
        assert adder.total_branches == 4
        assert adder.covered_branches == 4
        
    finally:
        temp_path.unlink()


def test_convenience_functions():
    """Test convenience functions"""
    from step5_coverage.parsers.verilator_parser import (
        create_verilator_parser,
        is_verilator_coverage_available,
    )
    
    # Test create_verilator_parser
    parser = create_verilator_parser()
    assert parser is not None
    
    # Test is_verilator_coverage_available
    # This will depend on system setup
    available = is_verilator_coverage_available()
    assert isinstance(available, bool)


def test_with_sample_data():
    """Test with actual sample data from requirements"""
    from step5_coverage.parsers.verilator_parser import VerilatorParser
    
    # This is the sample data from the requirements document
    sample_dat = """# Verilator coverage database
# Generated by Verilator 5.006
# Date: 2024-01-15 14:30:00

# Coverage data format:
# C <file> <line> <hits>
# L <line_num> <hits>
# B <branch_id> <hits>
# T <toggle_node> <0to1> <1to0>

SF:rtl/adder.sv
FN:8,adder
FNDA:1000,adder
FNF:1
FNH:1
DA:8,1000
DA:9,1000
DA:10,1000
DA:11,1000
DA:12,1000
DA:13,850
DA:14,850
DA:15,850
DA:16,750
DA:17,750
DA:18,750
DA:19,750
DA:20,1000
DA:21,150
DA:22,150
DA:23,0
DA:24,0
LF:15
LH:13
BRDA:15,0,0,850
BRDA:15,0,1,150
BRDA:18,0,0,750
BRDA:18,0,1,250
BRF:4
BRH:4
end_of_record
"""
    
    parser = VerilatorParser()
    
    with tempfile.NamedTemporaryFile(suffix='.dat', delete=False, mode='w') as f:
        f.write(sample_dat)
        temp_path = Path(f.name)
    
    try:
        result = parser.parse_file(temp_path)
        
        assert result.success
        assert result.coverage is not None
        
        # The sample shows 13 of 15 lines hit (86.7%)
        adder = result.coverage.files["rtl/adder.sv"]
        coverage_pct = adder.line_coverage_percent
        
        # Allow small floating point variation
        assert 86.0 <= coverage_pct <= 87.0
        
        print(f"✓ Sample data parsed: {coverage_pct:.1f}% line coverage")
        
    finally:
        temp_path.unlink()


if __name__ == "__main__":
    print("Testing Verilator parser...")
    
    test_can_parse()
    print("✓ Format detection")
    
    test_get_format()
    print("✓ Format identifier")
    
    test_parse_python()
    print("✓ Python parsing")
    
    test_parse_file()
    print("✓ Parse file")
    
    test_merge_python()
    print("✓ Python merging")
    
    test_validate_dat_file()
    print("✓ File validation")
    
    test_coverage_metrics()
    print("✓ Coverage metrics")
    
    test_convenience_functions()
    print("✓ Convenience functions")
    
    test_with_sample_data()
    print("✓ Sample data from requirements")
    
    print("\n✅ All Verilator parser tests passed!")
