"""
Python/cocotb Templates for UVM Translation.

Provides template code for common UVM patterns translated to cocotb/pyuvm.
"""

from typing import Dict, List, Optional, Any
from dataclasses import dataclass

from .analyzer import UVMTestbenchStructure, SignalInfo


@dataclass
class TemplateConfig:
    """Configuration for template generation."""
    dut_name: str = "dut"
    clock_signal: str = "clk"
    reset_signal: str = "rst_n"
    reset_active_low: bool = True
    clock_period_ns: int = 10
    data_width: int = 8


class CocotbTemplates:
    """
    Templates for generating cocotb testbench code.
    
    Provides reusable code patterns for:
    - Test infrastructure (clock, reset)
    - Drivers and monitors
    - Transactions
    - Scoreboards
    - Common test patterns
    """
    
    @staticmethod
    def get_header(module_name: str = "test_dut") -> str:
        """Get standard file header."""
        return f'''"""
{module_name} - cocotb testbench
Auto-generated by UVM Translator.
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, FallingEdge, ClockCycles, Timer, First
from cocotb.result import TestFailure
import random
from dataclasses import dataclass, field
from typing import List, Optional, Any
from collections import deque
import logging

# Configure logging
log = logging.getLogger(__name__)
log.setLevel(logging.INFO)

'''
    
    @staticmethod
    def get_reset_coroutine(config: TemplateConfig) -> str:
        """Get reset coroutine template."""
        reset_val = '0' if config.reset_active_low else '1'
        release_val = '1' if config.reset_active_low else '0'
        
        return f'''
async def reset_dut(dut, cycles: int = 5):
    """
    Apply reset to the DUT.
    
    Args:
        dut: cocotb DUT handle
        cycles: Number of clock cycles to hold reset
    """
    log.info("Applying reset...")
    dut.{config.reset_signal}.value = {reset_val}
    await ClockCycles(dut.{config.clock_signal}, cycles)
    dut.{config.reset_signal}.value = {release_val}
    await RisingEdge(dut.{config.clock_signal})
    log.info("Reset complete")

'''
    
    @staticmethod
    def get_clock_start(config: TemplateConfig) -> str:
        """Get clock start code."""
        return f'''    # Start clock
    cocotb.start_soon(Clock(dut.{config.clock_signal}, {config.clock_period_ns}, units='ns').start())
'''
    
    @staticmethod
    def get_transaction_class(name: str, fields: List[Dict[str, Any]]) -> str:
        """Generate a transaction dataclass."""
        import re
        field_defs = []
        random_code = []
        seen_fields = set()  # Track seen fields to avoid duplicates
        
        for f in fields:
            fname = f['name']
            
            # Skip invalid field names
            if not fname or not re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', fname):
                continue
            
            # Skip duplicates
            if fname in seen_fields:
                continue
            seen_fields.add(fname)
            
            # Skip Python keywords and builtins
            if fname in ('class', 'def', 'return', 'if', 'else', 'for', 'while', 
                        'try', 'except', 'import', 'from', 'None', 'True', 'False',
                        'and', 'or', 'not', 'in', 'is', 'lambda', 'pass', 'break',
                        'continue', 'raise', 'yield', 'with', 'as', 'global', 'self'):
                continue
            
            ftype = f.get('type', 'int')
            is_rand = f.get('is_rand', False)
            default = f.get('default', '0')
            
            # Sanitize default value
            if default and not re.match(r'^[0-9a-fA-FxX\'"]+$|^None$', str(default).strip()):
                default = '0'
            
            # Map SV types to Python
            py_type = 'int'
            if 'bit' in ftype.lower() or 'logic' in ftype.lower():
                py_type = 'int'
            elif 'string' in ftype.lower():
                py_type = 'str'
            
            field_defs.append(f"    {fname}: {py_type} = {default}")
            
            if is_rand:
                # Determine width for random bounds
                width = 8  # Default
                match = re.search(r'\[(\d+):(\d+)\]', ftype)
                if match:
                    width = int(match.group(1)) - int(match.group(2)) + 1
                
                max_val = (1 << width) - 1
                random_code.append(f"        self.{fname} = random.randint(0, {max_val})")
        
        fields_str = '\n'.join(field_defs)
        random_str = '\n'.join(random_code) if random_code else "        pass"
        
        return f'''
@dataclass
class {name}:
    """Transaction class for {name}."""
{fields_str}
    
    def randomize(self):
        """Randomize transaction fields."""
{random_str}
        return self
    
    def __str__(self) -> str:
        attrs = ", ".join(f"{{k}}={{v}}" for k, v in self.__dict__.items())
        return f"{name}({{attrs}})"

'''
    
    @staticmethod
    def get_driver_coroutine(name: str, signals: List[SignalInfo], 
                            transaction_name: str = "Transaction") -> str:
        """Generate a driver coroutine."""
        # Generate signal assignments
        assignments = []
        for sig in signals:
            if sig.direction == 'input':
                assignments.append(f"        dut.{sig.name}.value = trans.{sig.name}")
        
        assignments_str = '\n'.join(assignments) if assignments else "        # TODO: Add signal assignments"
        
        return f'''
class {name}:
    """
    Driver for sending transactions to DUT.
    """
    
    def __init__(self, dut, clock_signal: str = "clk"):
        self.dut = dut
        self.clock = getattr(dut, clock_signal)
        self.transaction_queue = deque()
    
    def send(self, trans: {transaction_name}):
        """Queue a transaction to be sent."""
        self.transaction_queue.append(trans)
    
    async def drive(self, trans: {transaction_name}):
        """Drive a single transaction to DUT."""
{assignments_str}
        await RisingEdge(self.clock)
        log.debug(f"Drove: {{trans}}")
    
    async def run(self):
        """Main driver loop - drives queued transactions."""
        while True:
            if self.transaction_queue:
                trans = self.transaction_queue.popleft()
                await self.drive(trans)
            else:
                await RisingEdge(self.clock)

'''
    
    @staticmethod
    def get_monitor_coroutine(name: str, signals: List[SignalInfo],
                             transaction_name: str = "Transaction") -> str:
        """Generate a monitor coroutine."""
        # Generate signal sampling
        samples = []
        for sig in signals:
            if sig.direction == 'output':
                samples.append(f"        trans.{sig.name} = int(dut.{sig.name}.value)")
        
        samples_str = '\n'.join(samples) if samples else "        # TODO: Add signal sampling"
        
        return f'''
class {name}:
    """
    Monitor for sampling DUT outputs.
    """
    
    def __init__(self, dut, clock_signal: str = "clk", callback=None):
        self.dut = dut
        self.clock = getattr(dut, clock_signal)
        self.callback = callback
        self.transactions = []
    
    async def sample(self) -> {transaction_name}:
        """Sample DUT outputs into a transaction."""
        trans = {transaction_name}()
{samples_str}
        return trans
    
    async def run(self):
        """Main monitor loop - samples on every clock."""
        while True:
            await RisingEdge(self.clock)
            trans = await self.sample()
            self.transactions.append(trans)
            if self.callback:
                self.callback(trans)
            log.debug(f"Sampled: {{trans}}")

'''
    
    @staticmethod
    def get_scoreboard_class(name: str = "Scoreboard") -> str:
        """Generate a scoreboard class."""
        return f'''
class {name}:
    """
    Scoreboard for comparing expected vs actual results.
    """
    
    def __init__(self):
        self.expected_queue = deque()
        self.actual_queue = deque()
        self.matches = 0
        self.mismatches = 0
        self.errors = []
    
    def add_expected(self, trans):
        """Add expected transaction."""
        self.expected_queue.append(trans)
    
    def add_actual(self, trans):
        """Add actual transaction from monitor."""
        self.actual_queue.append(trans)
        self._check()
    
    def _check(self):
        """Check for matches when both queues have items."""
        while self.expected_queue and self.actual_queue:
            expected = self.expected_queue.popleft()
            actual = self.actual_queue.popleft()
            
            if self._compare(expected, actual):
                self.matches += 1
                log.debug(f"Match: {{expected}}")
            else:
                self.mismatches += 1
                error_msg = f"Mismatch: expected={{expected}}, actual={{actual}}"
                self.errors.append(error_msg)
                log.error(error_msg)
    
    def _compare(self, expected, actual) -> bool:
        """Compare two transactions. Override for custom comparison."""
        return expected == actual
    
    def report(self) -> str:
        """Generate final report."""
        total = self.matches + self.mismatches
        return (
            f"Scoreboard Report:\\n"
            f"  Total comparisons: {{total}}\\n"
            f"  Matches: {{self.matches}}\\n"
            f"  Mismatches: {{self.mismatches}}\\n"
            f"  Pass rate: {{100*self.matches/total if total > 0 else 0:.1f}}%"
        )
    
    def check_empty(self):
        """Check that no transactions are left in queues."""
        if self.expected_queue:
            log.warning(f"{{len(self.expected_queue)}} expected transactions not matched")
        if self.actual_queue:
            log.warning(f"{{len(self.actual_queue)}} actual transactions not matched")

'''
    
    @staticmethod
    def get_test_template(test_name: str, description: str,
                         config: TemplateConfig) -> str:
        """Generate a test function template."""
        return f'''
@cocotb.test()
async def {test_name}(dut):
    """
    {description}
    """
{CocotbTemplates.get_clock_start(config)}
    await reset_dut(dut)
    
    # TODO: Add test logic here
    
    for i in range(10):
        await RisingEdge(dut.{config.clock_signal})
    
    cocotb.log.info("{test_name} completed")

'''
    
    @staticmethod
    def get_random_test_template(config: TemplateConfig,
                                transaction_name: str = "Transaction",
                                num_iterations: int = 100) -> str:
        """Generate a random stimulus test template."""
        return f'''
@cocotb.test()
async def test_random_stimulus(dut):
    """
    Test with randomized transactions.
    """
{CocotbTemplates.get_clock_start(config)}
    await reset_dut(dut)
    
    scoreboard = Scoreboard()
    
    for i in range({num_iterations}):
        # Generate random transaction
        trans = {transaction_name}().randomize()
        
        # Drive to DUT
        # TODO: Add appropriate signal assignments
        
        # Wait for result
        await RisingEdge(dut.{config.clock_signal})
        
        # Sample and check
        # TODO: Add result checking
    
    # Final check
    scoreboard.check_empty()
    cocotb.log.info(scoreboard.report())
    
    assert scoreboard.mismatches == 0, f"Test failed with {{scoreboard.mismatches}} mismatches"

'''
    
    @staticmethod  
    def get_coverage_test_template(config: TemplateConfig) -> str:
        """Generate a coverage-focused test template."""
        return f'''
@cocotb.test()
async def test_coverage_scenarios(dut):
    """
    Coverage-focused test hitting specific scenarios.
    """
{CocotbTemplates.get_clock_start(config)}
    await reset_dut(dut)
    
    # Scenario 1: Boundary conditions
    cocotb.log.info("Testing boundary conditions...")
    # TODO: Add boundary tests
    
    # Scenario 2: Corner cases
    cocotb.log.info("Testing corner cases...")
    # TODO: Add corner case tests
    
    # Scenario 3: Error injection
    cocotb.log.info("Testing error handling...")
    # TODO: Add error injection tests
    
    # Scenario 4: Back-to-back operations
    cocotb.log.info("Testing back-to-back operations...")
    for _ in range(10):
        await RisingEdge(dut.{config.clock_signal})
    
    cocotb.log.info("Coverage scenarios completed")

'''


class PyUVMTemplates:
    """
    Templates for generating pyuvm testbench code.
    
    Provides UVM-style patterns using pyuvm framework.
    """
    
    @staticmethod
    def get_header() -> str:
        """Get standard pyuvm file header."""
        return '''"""
pyuvm testbench
Auto-generated by UVM Translator.
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, FallingEdge, ClockCycles
from pyuvm import *
import random

'''
    
    @staticmethod
    def get_sequence_item(name: str, fields: List[Dict[str, Any]]) -> str:
        """Generate a pyuvm sequence item class."""
        field_defs = []
        for f in fields:
            fname = f['name']
            default = f.get('default', '0')
            field_defs.append(f"        self.{fname} = {default}")
        
        fields_str = '\n'.join(field_defs) if field_defs else "        pass"
        
        return f'''
class {name}(uvm_sequence_item):
    """Sequence item for {name}."""
    
    def __init__(self, name="{name}"):
        super().__init__(name)
{fields_str}
    
    def randomize(self):
        """Randomize fields."""
        # TODO: Add randomization with constraints
        return True

'''
    
    @staticmethod
    def get_driver(name: str, signals: List[SignalInfo]) -> str:
        """Generate a pyuvm driver class."""
        return f'''
class {name}(uvm_driver):
    """Driver for {name}."""
    
    def build_phase(self):
        self.bfm = ConfigDB().get(self, "", "BFM")
    
    async def run_phase(self):
        while True:
            item = await self.seq_item_port.get_next_item()
            await self.bfm.drive(item)
            self.seq_item_port.item_done()

'''
    
    @staticmethod
    def get_monitor(name: str) -> str:
        """Generate a pyuvm monitor class."""
        return f'''
class {name}(uvm_component):
    """Monitor for {name}."""
    
    def build_phase(self):
        self.bfm = ConfigDB().get(self, "", "BFM")
        self.ap = uvm_analysis_port("ap", self)
    
    async def run_phase(self):
        while True:
            item = await self.bfm.sample()
            self.ap.write(item)

'''
    
    @staticmethod
    def get_env(name: str, agents: List[str]) -> str:
        """Generate a pyuvm environment class."""
        agent_defs = '\n'.join([f"        self.{a} = {a}.create(\"{a}\", self)" for a in agents])
        
        return f'''
class {name}(uvm_env):
    """Environment for {name}."""
    
    def build_phase(self):
{agent_defs if agent_defs else "        pass"}
    
    def connect_phase(self):
        # Connect analysis ports to scoreboard
        pass

'''
    
    @staticmethod
    def get_test(name: str, env_name: str, sequence_name: str) -> str:
        """Generate a pyuvm test class."""
        return f'''
@pyuvm.test()
class {name}(uvm_test):
    """Test class for {name}."""
    
    def build_phase(self):
        self.env = {env_name}.create("{env_name}", self)
    
    async def run_phase(self):
        self.raise_objection()
        seq = {sequence_name}("{sequence_name}")
        await seq.start(self.env.agent.sequencer)
        self.drop_objection()

'''


def generate_complete_testbench(structure: UVMTestbenchStructure) -> str:
    """
    Generate a complete cocotb testbench from analyzed structure.
    
    Args:
        structure: Analyzed UVM testbench structure
        
    Returns:
        Complete Python testbench code
    """
    config = TemplateConfig(
        dut_name=structure.dut_name or "dut",
        clock_signal=structure.clock_signal,
        reset_signal=structure.reset_signal,
        reset_active_low=structure.reset_active_low,
        clock_period_ns=structure.clock_period_ns
    )
    
    code_parts = []
    
    # Header
    code_parts.append(CocotbTemplates.get_header())
    
    # Reset coroutine
    code_parts.append(CocotbTemplates.get_reset_coroutine(config))
    
    # Transaction classes
    for trans in structure.transactions:
        code_parts.append(CocotbTemplates.get_transaction_class(
            trans.name,
            trans.fields
        ))
    
    # If no transactions, create a generic one
    if not structure.transactions:
        code_parts.append(CocotbTemplates.get_transaction_class(
            "Transaction",
            [{'name': 'data', 'type': 'int', 'is_rand': True}]
        ))
    
    # Driver
    trans_name = structure.transactions[0].name if structure.transactions else "Transaction"
    code_parts.append(CocotbTemplates.get_driver_coroutine(
        "Driver",
        structure.interface_signals,
        trans_name
    ))
    
    # Monitor
    code_parts.append(CocotbTemplates.get_monitor_coroutine(
        "Monitor",
        structure.interface_signals,
        trans_name
    ))
    
    # Scoreboard
    code_parts.append(CocotbTemplates.get_scoreboard_class())
    
    # Tests
    code_parts.append(CocotbTemplates.get_test_template(
        "test_reset",
        "Test reset behavior",
        config
    ))
    
    code_parts.append(CocotbTemplates.get_test_template(
        "test_basic",
        "Test basic DUT operation",
        config
    ))
    
    code_parts.append(CocotbTemplates.get_random_test_template(config, trans_name))
    
    code_parts.append(CocotbTemplates.get_coverage_test_template(config))
    
    return '\n'.join(code_parts)

