"""
test_dut - cocotb testbench
Auto-generated by UVM Translator.
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, FallingEdge, ClockCycles, Timer, First
from cocotb.result import TestFailure
import random
from dataclasses import dataclass, field
from typing import List, Optional, Any
from collections import deque
import logging

# Configure logging
log = logging.getLogger(__name__)
log.setLevel(logging.INFO)



async def reset_dut(dut, cycles: int = 5):
    """
    Apply reset to the DUT.
    
    Args:
        dut: cocotb DUT handle
        cycles: Number of clock cycles to hold reset
    """
    log.info("Applying reset...")
    dut.rst_n.value = 0
    await ClockCycles(dut.clk, cycles)
    dut.rst_n.value = 1
    await RisingEdge(dut.clk)
    log.info("Reset complete")



@dataclass
class sync_fifo_seq_item:
    """Transaction class for sync_fifo_seq_item."""
    wr_en: int = None
    rd_en: int = None
    wr_data: int = None
    rd_data: int = None
    full: int = None
    empty: int = None
    almost_full: int = None
    almost_empty: int = None
    count: int = None
    name: str = 0
    s: str = None
    
    def randomize(self):
        """Randomize transaction fields."""
        self.wr_en = random.randint(0, 255)
        self.rd_en = random.randint(0, 255)
        self.wr_data = random.randint(0, 4294967295)
        return self
    
    def __str__(self) -> str:
        attrs = ", ".join(f"{k}={v}" for k, v in self.__dict__.items())
        return f"sync_fifo_seq_item({attrs})"



@dataclass
class fifo_bus_transaction:
    """Transaction class for fifo_bus_transaction."""
    addr: int = None
    data: int = None
    kind: int = None
    name: str = 0
    rhs_: int = None
    r: int = 0
    a: int = 0
    d: int = 0
    s: str = None
    
    def randomize(self):
        """Randomize transaction fields."""
        self.addr = random.randint(0, 4294967295)
        self.data = random.randint(0, 4294967295)
        self.kind = random.randint(0, 255)
        return self
    
    def __str__(self) -> str:
        attrs = ", ".join(f"{k}={v}" for k, v in self.__dict__.items())
        return f"fifo_bus_transaction({attrs})"



class Driver:
    """
    Driver for sending transactions to DUT.
    """
    
    def __init__(self, dut, clock_signal: str = "clk"):
        self.dut = dut
        self.clock = getattr(dut, clock_signal)
        self.transaction_queue = deque()
    
    def send(self, trans: sync_fifo_seq_item):
        """Queue a transaction to be sent."""
        self.transaction_queue.append(trans)
    
    async def drive(self, trans: sync_fifo_seq_item):
        """Drive a single transaction to DUT."""
        dut.rd_data.value = trans.rd_data
        dut.full.value = trans.full
        dut.empty.value = trans.empty
        dut.almost_full.value = trans.almost_full
        dut.almost_empty.value = trans.almost_empty
        dut.count.value = trans.count
        dut.wr_en.value = trans.wr_en
        dut.rd_en.value = trans.rd_en
        dut.wr_data.value = trans.wr_data
        dut.rd_data.value = trans.rd_data
        dut.full.value = trans.full
        dut.empty.value = trans.empty
        dut.almost_full.value = trans.almost_full
        dut.almost_empty.value = trans.almost_empty
        dut.count.value = trans.count
        dut.rd_data.value = trans.rd_data
        dut.full.value = trans.full
        dut.empty.value = trans.empty
        dut.almost_full.value = trans.almost_full
        dut.almost_empty.value = trans.almost_empty
        dut.count.value = trans.count
        dut.wr_en.value = trans.wr_en
        dut.rd_en.value = trans.rd_en
        dut.wr_data.value = trans.wr_data
        dut.rd_data.value = trans.rd_data
        dut.full.value = trans.full
        dut.empty.value = trans.empty
        dut.almost_full.value = trans.almost_full
        dut.almost_empty.value = trans.almost_empty
        dut.count.value = trans.count
        await RisingEdge(self.clock)
        log.debug(f"Drove: {trans}")
    
    async def run(self):
        """Main driver loop - drives queued transactions."""
        while True:
            if self.transaction_queue:
                trans = self.transaction_queue.popleft()
                await self.drive(trans)
            else:
                await RisingEdge(self.clock)



class Monitor:
    """
    Monitor for sampling DUT outputs.
    """
    
    def __init__(self, dut, clock_signal: str = "clk", callback=None):
        self.dut = dut
        self.clock = getattr(dut, clock_signal)
        self.callback = callback
        self.transactions = []
    
    async def sample(self) -> sync_fifo_seq_item:
        """Sample DUT outputs into a transaction."""
        trans = sync_fifo_seq_item()
        trans.wr_en = int(dut.wr_en.value)
        trans.rd_en = int(dut.rd_en.value)
        trans.wr_data = int(dut.wr_data.value)
        trans.wr_en = int(dut.wr_en.value)
        trans.rd_en = int(dut.rd_en.value)
        trans.wr_data = int(dut.wr_data.value)
        return trans
    
    async def run(self):
        """Main monitor loop - samples on every clock."""
        while True:
            await RisingEdge(self.clock)
            trans = await self.sample()
            self.transactions.append(trans)
            if self.callback:
                self.callback(trans)
            log.debug(f"Sampled: {trans}")



class Scoreboard:
    """
    Scoreboard for comparing expected vs actual results.
    """
    
    def __init__(self):
        self.expected_queue = deque()
        self.actual_queue = deque()
        self.matches = 0
        self.mismatches = 0
        self.errors = []
    
    def add_expected(self, trans):
        """Add expected transaction."""
        self.expected_queue.append(trans)
    
    def add_actual(self, trans):
        """Add actual transaction from monitor."""
        self.actual_queue.append(trans)
        self._check()
    
    def _check(self):
        """Check for matches when both queues have items."""
        while self.expected_queue and self.actual_queue:
            expected = self.expected_queue.popleft()
            actual = self.actual_queue.popleft()
            
            if self._compare(expected, actual):
                self.matches += 1
                log.debug(f"Match: {expected}")
            else:
                self.mismatches += 1
                error_msg = f"Mismatch: expected={expected}, actual={actual}"
                self.errors.append(error_msg)
                log.error(error_msg)
    
    def _compare(self, expected, actual) -> bool:
        """Compare two transactions. Override for custom comparison."""
        return expected == actual
    
    def report(self) -> str:
        """Generate final report."""
        total = self.matches + self.mismatches
        return (
            f"Scoreboard Report:\n"
            f"  Total comparisons: {total}\n"
            f"  Matches: {self.matches}\n"
            f"  Mismatches: {self.mismatches}\n"
            f"  Pass rate: {100*self.matches/total if total > 0 else 0:.1f}%"
        )
    
    def check_empty(self):
        """Check that no transactions are left in queues."""
        if self.expected_queue:
            log.warning(f"{len(self.expected_queue)} expected transactions not matched")
        if self.actual_queue:
            log.warning(f"{len(self.actual_queue)} actual transactions not matched")



@cocotb.test()
async def test_reset(dut):
    """
    Test reset behavior
    """
    # Start clock
    cocotb.start_soon(Clock(dut.clk, 10, units='ns').start())

    await reset_dut(dut)
    
    # TODO: Add test logic here
    
    for i in range(10):
        await RisingEdge(dut.clk)
    
    cocotb.log.info("test_reset completed")



@cocotb.test()
async def test_basic(dut):
    """
    Test basic DUT operation
    """
    # Start clock
    cocotb.start_soon(Clock(dut.clk, 10, units='ns').start())

    await reset_dut(dut)
    
    # TODO: Add test logic here
    
    for i in range(10):
        await RisingEdge(dut.clk)
    
    cocotb.log.info("test_basic completed")



@cocotb.test()
async def test_random_stimulus(dut):
    """
    Test with randomized transactions.
    """
    # Start clock
    cocotb.start_soon(Clock(dut.clk, 10, units='ns').start())

    await reset_dut(dut)
    
    scoreboard = Scoreboard()
    
    for i in range(100):
        # Generate random transaction
        trans = sync_fifo_seq_item().randomize()
        
        # Drive to DUT
        # TODO: Add appropriate signal assignments
        
        # Wait for result
        await RisingEdge(dut.clk)
        
        # Sample and check
        # TODO: Add result checking
    
    # Final check
    scoreboard.check_empty()
    cocotb.log.info(scoreboard.report())
    
    assert scoreboard.mismatches == 0, f"Test failed with {scoreboard.mismatches} mismatches"



@cocotb.test()
async def test_coverage_scenarios(dut):
    """
    Coverage-focused test hitting specific scenarios.
    """
    # Start clock
    cocotb.start_soon(Clock(dut.clk, 10, units='ns').start())

    await reset_dut(dut)
    
    # Scenario 1: Boundary conditions
    cocotb.log.info("Testing boundary conditions...")
    # TODO: Add boundary tests
    
    # Scenario 2: Corner cases
    cocotb.log.info("Testing corner cases...")
    # TODO: Add corner case tests
    
    # Scenario 3: Error injection
    cocotb.log.info("Testing error handling...")
    # TODO: Add error injection tests
    
    # Scenario 4: Back-to-back operations
    cocotb.log.info("Testing back-to-back operations...")
    for _ in range(10):
        await RisingEdge(dut.clk)
    
    cocotb.log.info("Coverage scenarios completed")

